cache:
  directories:
  - node_modules
language: node_js
node_js: 7
branches:
  only:
  - master
script:
  - yarn install
  - yarn test
  - yarn build
install: yarn global add firebase-tools
after_success:
  - firebase use --token ${FIREBASE_TOKEN}
  - firebase use --add ${PROJECT_ID}
  - firebase deploy --non-interactive --token "${FIREBASE_TOKEN}"
notifications:
  webhooks:
    urls:
    - https://api.ghostinspector.com/v1/suites/5981a3d3ed42cd3010099697/execute/?apiKey=a9baa3187c5bbae79b492d3e60bc2ca9068f2cba
    on_success: always
    on_failure: never
  slack:
    secure: TcnPitQG4xc4jtrWPLsv9im4qL89xRfURlz7cEB0QvQNhAF+w8vlg60Rt3zz8kvQXLJ1euIIdTtutQhjxMF6MutXcFywp8M9fR/ajKTG3MCVdhYizOh60bt8rGuf0CNim/mAXapTJ1Aj072/QM5g0jUua7kkEHiqHn3VcX0il60fNO3dPV7PJT9YCMEasBRaIBF71S7lowqDUiY49u1Smjm+TRz1AGAfB7Yt4nxAW/8+DuUSuP8xHeXcFzSOW568ISvuWGasNuD5hd9q6buHcB78H+pGjd5vHzy3e3pc1u571uoYqdIZcpbzaaQNVzA66Dzu1ynIXsPHmps/MfnVNg8zhSugscBt92n0A2mF2OowrWqEjYuSsxr+bQm8CPH7QsDEpfao2Tcl+jeqsBbZ1gMKPX/NM6+cHLF31+iCwSfhxy2bvbMrEmj6DwZDVZTnIJcSzG0t+25b3y4gVUE5UainjksfPgKnlZeFOEdiM6Robj24Zw8MOFWw/fsNubzf0TrVeIwZbVr9ESy8rxQQ9+Zh2jsYUkC6hGstPIsFoSoaDbeE1R6wCvjc1EqKvsS65kD6yJAMxUR/DGqB3RFoCYAX2SG4l7evqdCw8kpZ9L/QmHEEknne4lZRVy144VGQs8d7FBgBXLN649QV5rQCNMGHprEfJo7YlazwrUYjVzo=
